### ISSUE TITLE
Reolink IP Device integration hangs periodically, only a manual reboot helps.

### ISSUE THREAD

**Issue by vit-um** [xannor/ha_reolink_rest#34]
Camera RLC-811A
Прошивка: v3.1.0.989_22051908
Апаратне забезпечення: IPC_523128M8MP

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/reolink_rest/number.py:214
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:08:12 (4 occurrences)
Last logged: 14:15:56

[546611246752] ('Set PTZ Zoom/Focus failed', 'please login first')
[546720778704] ('Set PTZ Zoom/Focus failed', 'please login first')
[546611054816] ('Set PTZ Zoom/Focus failed', 'please login first')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 109, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/reolink_rest/number.py", line 214, in async_set_native_value
    await client.set_ptz_zoomfocus(int(value), _op, self._channel_id)
  File "/usr/local/lib/python3.10/site-packages/async_reolink/api/ptz/__init__.py", line 251, in set_ptz_zoomfocus
    response.throw("Set PTZ Zoom/Focus failed")
  File "/usr/local/lib/python3.10/site-packages/async_reolink/api/commands/__init__.py", line 40, in throw
    raise ReolinkResponseError(*args, code=self.error_code, details=self.details)
async_reolink.api.errors.ReolinkResponseError: ('Set PTZ Zoom/Focus failed', 'please login first')

**Comment by xannor** [comment]
After some testing, and limited time. I think I am going to put this on hiatus, I would recommend using the built in version as it has fundamentally surpassed what I have built and will have better support than I can provide.
