### ISSUE TITLE
Unexpected error when trying to add 810a

### ISSUE THREAD

**Issue by satellite-no** [xannor/ha_reolink_rest#38]
Trying to add camera RLC-810A to integrations but seeing `Unexpected error` when i input `ip` for host and 443 for port on device setup.  Below error is recorded in home-assistant.log thoughts? 

```text
Traceback (most recent call last):
  File "/config/custom_components/reolink_rest/config_flow.py", line 204, in async_step_user
    if not await client.login(
  File "/usr/local/lib/python3.10/site-packages/async_reolink/api/security/__init__.py", line 71, in login
    async for response in self._execute(
  File "/usr/local/lib/python3.10/site-packages/async_reolink/rest/connection.py", line 252, in __execute
    response = await context
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 990, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host 10.1.0.172:443 ssl:default [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)]
```

**Comment by xannor** [comment]
You either need to disable SSL and use just HTTP or install a proper SSL cert. The self signed certs the camera use are considered very weak and Pyhton 3.10 does not allow them by default. (That is what the HANDSHAKE_FAILURE means)

**Comment by satellite-no** [comment]
Good call!! Thanks
