### ISSUE TITLE
Cannot add device (RLC-510WA)

### ISSUE THREAD

**Issue by luisiam** [xannor/ha_reolink_rest#39]
Hi, I am trying to add RLC-510WA via this integration but I keep getting the error `A device communication error occurred and setup cannot complete`

Log:
```
Logger: custom_components.reolink_rest.config_flow
Source: custom_components/reolink_rest/config_flow.py:204
Integration: Reolink IP Device ([documentation](https://github.com/xannor/ha_reolink_rest), [issues](https://github.com/xannor/ha_reolink_rest/issues))
First occurred: 10:03:59 PM (1 occurrences)
Last logged: 10:03:59 PM

An internal device error occurred on 192.168.10.23, configuration aborting
Traceback (most recent call last):
  File "/config/custom_components/reolink_rest/config_flow.py", line 204, in async_step_user
    if not await client.login(
  File "/usr/local/lib/python3.10/site-packages/async_reolink/api/security/__init__.py", line 78, in login
    response.throw("Login request failed")
  File "/usr/local/lib/python3.10/site-packages/async_reolink/api/commands/__init__.py", line 40, in throw
    raise ReolinkResponseError(*args, code=self.error_code, details=self.details)
async_reolink.api.errors.ReolinkResponseError: ('Login request failed', 'busy')
```

**Comment by xannor** [comment]
Busy is a new one.Try rebooting the camera (either through the web interface or hard powering it.)

**Comment by DezzyTee** [comment]
Same problem here with the RLC-823A

**Comment by luisiam** [comment]
Looks like reolink doesn't like special character in the password. After removing the `!` in my password, every works as expected. Suggest to add that to readme.

**Comment by xannor** [comment]
An ! Should be an ok character, it could be an encoding issue, I will have to test that to see.

**Comment by luisiam** [comment]
I have the same issue when using scrypted since `!` will be encoded to `%21`. Looks like the Reolink FW does not handle that properly.

**Comment by xannor** [comment]
After some testing, and limited time. I think I am going to put this on hiatus, I would recommend using the built in version as it has fundamentally surpassed what I have built and will have better support than I can provide.
