### ISSUE TITLE
PTZ Zoom/Focus failed for RLC-811A

### ISSUE THREAD

**Issue by vit-um** [xannor/ha_reolink_rest#43]
Ні!

Integration periodically hangs with the error described below. At the same time, motion sensors and zoom control stop working. After restarting the integration, the functionality is restored. Maybe you can come up with some kind of watchdog or tweak something in the settings?

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/reolink_rest/number.py:214
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:40:39 (5 occurrences)
Last logged: 20:46:26

[546363340592] ('Set PTZ Zoom/Focus failed', 'please login first')
[546362747408] ('Set PTZ Zoom/Focus failed', 'please login first')
[546596096560] ('Set PTZ Zoom/Focus failed', 'please login first')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 720, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 96, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/reolink_rest/number.py", line 214, in async_set_native_value
    await client.set_ptz_zoomfocus(int(value), _op, self._channel_id)
  File "/usr/local/lib/python3.10/site-packages/async_reolink/api/ptz/__init__.py", line 251, in set_ptz_zoomfocus
    response.throw("Set PTZ Zoom/Focus failed")
  File "/usr/local/lib/python3.10/site-packages/async_reolink/api/commands/__init__.py", line 40, in throw
    raise ReolinkResponseError(*args, code=self.error_code, details=self.details)
async_reolink.api.errors.ReolinkResponseError: ('Set PTZ Zoom/Focus failed', 'please login first')

**Comment by xannor** [comment]
PTZ will be added soon the the "official" integration so I would recommend waiting for that one as I am unsure if I will continue work on this as that one has more dedicated development than I can provide.
